#!/usr/bin/env python3
"""Write CHANGELOG.md from main's first-parent history: one line per merged change.

    python3 src/etc/changelog.py                 # rewrite CHANGELOG.md from origin/main
    python3 src/etc/changelog.py --ref=main --stdout   # another ref, print only

Packet W1, 8 Oct 2026. Accurate by construction: every line is a commit subject on main
with its date and pull request number, nothing typed by hand. Commits pushed straight to
main (keepalive, community watch) are marked "direct". Needs full history (not a shallow
clone); packet controllers rerun it after each merge. App releases have their own notes
on each GitHub release; this file is the repository's history.
"""
import re
import subprocess
import sys
from pathlib import Path

REPO = 'https://github.com/govinda-rajulu/patch-factory'
HEADER = '''# Changelog

Generated by `src/etc/changelog.py` from main's first-parent history. Do not edit by hand.
Each line is one change that reached main: date (UTC), subject, pull request. "direct" marks
a bot commit pushed to main without a pull request. App builds are not listed here: every
GitHub release carries its own notes (app version, applied patches, provider bundle, hashes).
Packet context lives in `knowledge/STATE.md` and `docs/review/`.
'''


MERGE = re.compile(r'^Merge pull request #(\d+) from \S+$')
# Before 29 Sep 2026 PRs were merged by hand as "Merge PR #N: title" (W4).
LEGACY = re.compile(r'^Merge PR #(\d+):\s*(.+)$')
SQUASH = re.compile(r'\s*\(#(\d+)\)\s*$')


def parse(sha, day, subject, body=''):
    """One history row. A squash merge ends its subject with "(#N)"; a merge commit's
    subject is "Merge pull request #N from owner/branch" and its first body line is the
    pull request title (W3, 8 Oct 2026: #158 was merged that way and listed as "direct")."""
    m = MERGE.match(subject.strip())
    if m:
        title = next((l.strip() for l in body.splitlines() if l.strip()), '') or subject
        return (day, sha, title, int(m[1]))
    m = LEGACY.match(subject.strip())
    if m:
        return (day, sha, m[2].strip(), int(m[1]))
    m = SQUASH.search(subject)
    return (day, sha, SQUASH.sub('', subject), m and int(m[1]))


def history(ref='HEAD'):
    shallow = subprocess.run(['git', 'rev-parse', '--is-shallow-repository'], capture_output=True, text=True)
    if shallow.stdout.strip() == 'true':
        raise SystemExit('shallow clone: fetch full history first (git fetch --unshallow)')
    out = subprocess.run(['git', 'log', '--first-parent', '--date=short', '--format=%h%x1f%ad%x1f%s%x1f%b%x1e', ref],
                         capture_output=True, text=True, check=True).stdout
    rows = []
    for rec in out.split('\x1e'):
        rec = rec.strip('\n')
        if not rec:
            continue
        sha, day, subject, body = (rec.split('\x1f') + ['', '', '', ''])[:4]
        rows.append(parse(sha, day, subject, body))
    return rows


def render(rows):
    lines = [HEADER]
    day = None
    for d, sha, subject, pr in rows:
        if d != day:
            lines.append('\n## %s\n' % d)
            day = d
        subject = subject.replace('|', '/').strip()
        ref = '[#%d](%s/pull/%d)' % (pr, REPO, pr) if pr else 'direct `%s`' % sha
        lines.append('- %s (%s)' % (subject, ref))
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    ref = next((a.split('=', 1)[1] for a in sys.argv if a.startswith('--ref=')), 'origin/main')
    if subprocess.run(['git', 'rev-parse', '--verify', '--quiet', ref], capture_output=True).returncode:
        raise SystemExit('unknown ref %s' % ref)
    text = render(history(ref))
    if '--stdout' in sys.argv:
        sys.stdout.write(text)
    else:
        Path('CHANGELOG.md').write_text(text, encoding='utf-8')
        print('CHANGELOG.md: %d entries' % text.count('\n- '))
