#!/usr/bin/env python3
"""Which community providers list a package? Read-only scout over src/community/bundles.json.

    python3 src/etc/onboard_scout.py com.amazon.mp3 com.linkedin.android

Packet W1, 8 Oct 2026. The community index (community-watch) records ~200 provider
bundles. This prints, per package, every index entry whose JSON mentions the package
and the patch names found next to it. It is a lead list for an onboarding record, not
evidence that a patch applies: that needs the provider's own list-patches run (-x -u).
The index schema is not assumed; entries are found by walking the JSON.
"""
import json
import sys
from pathlib import Path

INDEX = Path('src/community/bundles.json')
LABEL_KEYS = ('repository', 'repo', 'source', 'url', 'name', 'id')


def entries(data):
    if isinstance(data, list):
        return [(str(i), e) for i, e in enumerate(data)]
    if isinstance(data, dict):
        lists = [v for v in data.values() if isinstance(v, list) and v and all(isinstance(x, dict) for x in v)]
        if len(lists) == 1:
            return [(str(i), e) for i, e in enumerate(lists[0])]
        return [(str(k), v) for k, v in data.items() if isinstance(v, (dict, list))]
    return []


def label(key, entry):
    if isinstance(entry, dict):
        for k in LABEL_KEYS:
            v = entry.get(k)
            if isinstance(v, str) and v:
                return v
    return key


def mentions(node, package):
    if isinstance(node, str):
        return node == package
    if isinstance(node, dict):
        return any(mentions(v, package) for v in node.values()) or package in node
    if isinstance(node, list):
        return any(mentions(v, package) for v in node)
    return False


def patch_names(node, package, out):
    """Names of the smallest dicts that carry a 'name' and mention the package."""
    if isinstance(node, dict):
        if isinstance(node.get('name'), str) and any(mentions(v, package) for k, v in node.items() if k != 'name'):
            out.add(node['name'])
        for v in node.values():
            patch_names(v, package, out)
    elif isinstance(node, list):
        for v in node:
            patch_names(v, package, out)
    return out


def scout(data, packages):
    found = {p: [] for p in packages}
    for key, entry in entries(data):
        for p in packages:
            if mentions(entry, p):
                found[p].append({'provider': label(key, entry), 'names': sorted(patch_names(entry, p, set()))})
    return found


def render(found, source):
    lines = ['# Onboarding scout (generated)', '',
             'Generated by `src/etc/onboard_scout.py` from `%s`. Leads only: a listed name is not' % source,
             'proof that a patch applies. Verify with the provider\'s own list-patches output.', '']
    for p, rows in found.items():
        lines.append('## `%s`: %d provider(s) in the index' % (p, len(rows)))
        lines.append('')
        if not rows:
            lines.append('No provider in the community index lists this package.')
        for r in rows:
            lines.append('- **%s**: %s' % (r['provider'], ', '.join('`%s`' % n for n in r['names'][:40]) or '(no patch names found)'))
        lines.append('')
    return '\n'.join(lines)


def main(argv):
    packages = [a for a in argv if not a.startswith('--')]
    out = next((a.split('=', 1)[1] for a in argv if a.startswith('--out=')), None)
    if not packages:
        print('usage: onboard_scout.py PACKAGE [PACKAGE...] [--out=FILE]')
        return 2
    if not INDEX.is_file():
        print('::error::%s missing' % INDEX)
        return 1
    found = scout(json.loads(INDEX.read_text(encoding='utf-8')), packages)
    text = render(found, INDEX)
    if out:
        Path(out).write_text(text, encoding='utf-8')
    print(text)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
