#!/usr/bin/env python3
"""One table of every scheduled automation, in IST, newest rule first (packet W7, 9 Oct 2026).

Owner ask: group the schedules in one place. The table is generated from the workflow files,
so it cannot drift: Validate runs `--check`. Times come from the cron itself (UTC + 5:30);
the IST comment beside each cron is checked separately by tests/schedule_contracts.py.

    python3 src/etc/schedules.py           # rewrite docs/SCHEDULES.md
    python3 src/etc/schedules.py --check   # fail when docs/SCHEDULES.md is stale
"""
import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'docs/SCHEDULES.md'
CRON = re.compile(r'^\s+- cron: "([0-9]{1,2}) ([0-9]{1,2}) ([0-9*]+) ([*]) ([0-9*]+)"')
NAME = re.compile(r'^name: (.+)$', re.M)
SHORT = {'ci.yml': 'Full daily check: every provider, then builds the apps that changed.',
         'status.yml': 'Writes status.json for the Pages Builds and Watch tabs.',
         'council.yml': 'Agent council: one audit shard on the desk issue (Monday morning run: triage).'}
DAYS = {'0': 'Sunday', '1': 'Monday', '2': 'Tuesday', '3': 'Wednesday', '4': 'Thursday', '5': 'Friday', '6': 'Saturday'}


def purposes():
    spec = importlib.util.spec_from_file_location('pf_status_purpose', ROOT / 'src/etc/status.py')
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.PURPOSE


def rows():
    out = []
    for wf in sorted((ROOT / '.github/workflows').glob('*.yml')):
        text = wf.read_text(encoding='utf-8')
        name = NAME.search(text)
        for line in text.splitlines():
            m = CRON.match(line)
            if not m:
                continue
            minute, hour, dom, _, dow = m.groups()
            total = (int(hour) * 60 + int(minute) + 330) % 1440
            if dom != '*' and dow == '*':
                days = 'day %s of each month' % dom
            elif dow != '*' and dom == '*':
                days = DAYS[dow] + 's'
            elif dom == '*' and dow == '*':
                days = 'daily'
            else:
                raise SystemExit('unsupported cron in %s: %s' % (wf.name, line.strip()))
            note = line.split('#', 1)[1].strip() if '#' in line else ''
            note = re.sub(r'^[0-9]{2}:[0-9]{2} IST\s*', '', note).lstrip(':;, ')
            out.append((total, days, name[1].strip() if name else wf.name, wf.name, note))
    order = lambda d: 0 if d == 'daily' else 1 if d.endswith('days') else 2
    return sorted(out, key=lambda r: (order(r[1]), r[0]))


def render():
    purpose = purposes()
    lines = ['# Schedules', '',
             'Generated by `src/etc/schedules.py` from `.github/workflows/`; do not edit by hand.',
             'Times are IST (UTC + 5:30). GitHub may start a scheduled run late, sometimes by hours.', '',
             '| IST | When | Automation | What it does |', '| --- | --- | --- | --- |']
    for total, days, name, file, note in rows():
        what = SHORT.get(file) or purpose.get(file, '')
        if 'poll-only' in note:
            what, note = 'Quick poll: builds only the apps whose providers changed.', ''
        lines.append('| %02d:%02d | %s | %s (`%s`) | %s |' % (total // 60, total % 60, days, name, file, what))
    lines += ['', 'Everything else runs on request or after another run: Manual Patch, Batch Patch, '
              'Explore, Add target, Validate (every change), Notify on failure, Status page data '
              '(after each listed run), Onboarding review, Qualify published shadow baselines.', '']
    return '\n'.join(lines)


def main(argv):
    text = render()
    if '--check' in argv:
        if not OUT.exists() or OUT.read_text(encoding='utf-8') != text:
            print('::error::docs/SCHEDULES.md is stale. Run: python3 src/etc/schedules.py')
            return 1
        print('docs/SCHEDULES.md current (%d schedules)' % len(rows()))
        return 0
    OUT.write_bytes(text.encode('utf-8'))
    print('wrote docs/SCHEDULES.md (%d schedules)' % len(rows()))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
