/* Pure page contracts through Node's standard library; no network or Android runtime. */
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'docs/portal.js'),'utf8'),html=fs.readFileSync(path.join(root,'docs/index.html'),'utf8');
const marker='// Expose pure contracts only for tests';assert.equal(source.split(marker).length,2);
const context={window:{},document:{getElementById:()=>null},URL,Map,Set,Date,JSON,console,setTimeout,clearTimeout,AbortController};
vm.runInNewContext(source.slice(0,source.indexOf(marker))+'window.contracts={parseTag,validateImport,validateTargets,releaseRows,safeLink,selectApps,appGroup};})();',context);
const c=context.window.contracts,targets=JSON.parse(fs.readFileSync(path.join(root,'src/targets.json'))),pack=JSON.parse(fs.readFileSync(path.join(root,'docs/obtainium-govind.json'))),parents=JSON.parse(fs.readFileSync(path.join(root,'docs/obtainium-parents.json')));
let count=0;function check(name,fn){fn();count++;console.log('PASS '+name)}
check('catalog and full import have exact enabled coverage',()=>{assert.equal(c.validateTargets(targets).length,14);assert.equal(c.validateImport(pack,targets,'govind').length,14);assert.equal(c.validateImport(parents,targets,'parents').length,7)});
check('import encoded URI round trip retains full and selected app settings',()=>{const apps=c.validateImport(pack,targets,'govind'),uri='obtainium://apps/'+encodeURIComponent(JSON.stringify(apps));assert.deepEqual(JSON.parse(decodeURIComponent(uri.slice(17))),pack.apps);assert.ok(uri.length<100000);const before=JSON.stringify(apps);const chosen=c.selectApps(apps,[apps[2].id,apps[0].id]);assert.deepEqual(JSON.parse(JSON.stringify(chosen)),[pack.apps[0],pack.apps[2]]);assert.equal(JSON.stringify(apps),before);for(const ids of [[],['unknown'],[apps[0].id,apps[0].id],null])assert.throws(()=>c.selectApps(apps,ids));assert.equal(c.selectApps(apps,apps.map(a=>a.id)).length,14)});
check('malformed imports refuse global settings, duplicates, foreign URLs and credentials',()=>{for(const mutate of [d=>d.settings={},d=>d.apps.pop(),d=>d.apps.push(d.apps[0]),d=>d.apps[0].url='https://evil.invalid',d=>d.apps[0].additionalSettings='{"token":"SECRET"}']){const d=structuredClone(pack);mutate(d);assert.throws(()=>c.validateImport(d,targets,'govind'))}});
check('version and arbitrary precision build ID remain separate',()=>{const d=c.parseTag('youtube-morphe-v21.36.45-b2026091300000000034768808230000001');assert.equal(d.version,'21.36.45');assert.equal(d.run,'34768808230');assert.equal(d.attempt,'1');assert.equal(c.parseTag('app-v1.0-b2026091399999999999999999999000001').run,'99999999999999999999')});
check('legacy date tags accepted; malformed tags rejected',()=>{assert.equal(c.parseTag('app-v1.0-b20260913').run,null);for(const t of ['app-v1.0-b20260230','app-v1.0-b2026091300000000000000000000000000','app-v1<script>','app-v1.0-b20260913junk',null])assert.equal(c.parseTag(t),null)});
check('unsafe and cross-repository links refused',()=>{for(const url of ['javascript:alert(1)','http://github.com/'+ 'govinda-rajulu/patch-factory/releases','https://github.com/other/repo/releases','https://github.com.evil.invalid/govinda-rajulu/patch-factory/releases','https://user:pass@github.com/govinda-rajulu/patch-factory/releases'])assert.equal(c.safeLink(url),null)});
check('release grouping stays per target and ambiguous assets withheld',()=>{const tag='youtube-morphe-v21.36.45-b20260913',r={id:1,tag_name:tag,draft:false,prerelease:false,published_at:'2026-09-13T00:00:00Z',assets:[{name:'youtube-v21.36.45-arm64-v8a.apk',state:'uploaded',size:2000000,browser_download_url:'https://github.com/govinda-rajulu/patch-factory/releases/download/'+tag+'/youtube-v21.36.45-arm64-v8a.apk'}]};assert.equal(c.releaseRows([r],targets).map.get('youtube-morphe').length,1);assert.equal(c.releaseRows([r],targets).map.get('instagram').length,0);r.assets.push(r.assets[0]);assert.equal(c.releaseRows([r],targets).rejected,1)});
check('no credential input, persistent-token use or API write path',()=>{for(const s of ['localStorage','sessionStorage','innerHTML','insertAdjacentHTML','/dispatches','Authorization','method:'])assert.ok(!source.includes(s),s);assert.ok(!html.includes('type="password"'));assert.ok(html.includes('portal.js'));assert.ok(source.includes('credentials:\'omit\''))});
check('disabled or duplicate targets refused for full imports',()=>{let t=structuredClone(targets);t[0].enabled=false;assert.throws(()=>c.validateImport(pack,t,'govind'));t=structuredClone(targets);t.push(t[0]);assert.throws(()=>c.validateTargets(t));assert.equal(c.appGroup('youtube')[0],'media');assert.equal(c.appGroup('instagram')[0],'social');assert.equal(c.appGroup('keymapper')[0],'tools');assert.equal(c.appGroup('future-app')[0],'other');for(const marker of ['Search apps','Filter app category','Build details & older versions','No matching apps.'])assert.ok(source.includes(marker),marker)});
console.log('PORTAL_CONTRACTS_PASS='+count);
