name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "Patched YouTube, arm64-v8a, built from [Morphe patches](https://github.com/MorpheApp/morphe-patches/releases)."> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: |
          ./release/*.apk
        name: Revanced & Revanced Extended
        tag: all
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
